# Generated by Django 3.0.4 on 2020-04-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=16)),
                ('c_girl_num', models.IntegerField(default=5)),
                ('c_boy_num', models.IntegerField(default=3)),
            ],
        ),
    ]
