# Generated by Django 3.0.4 on 2020-04-01 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0006_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='c_cost',
        ),
    ]
