# Generated by Django 3.0.4 on 2020-04-01 22:48

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0007_remove_animal_c_cost'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='animal',
            managers=[
                ('a_m', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
