# Generated by Django 3.0.4 on 2020-04-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0008_auto_20200401_2248'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='animal',
            managers=[
            ],
        ),
    ]
