# Generated by Django 3.0.4 on 2020-04-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0002_auto_20200406_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=16)),
                ('g_customer', models.ManyToManyField(to='Two.Customer')),
            ],
        ),
    ]
